server:
  port: 8020

spring:
  application:
    name: mc-product
  config:
    import: optional:configserver:http://localhost:8888

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/product_db
    username: product_user
    password: product_pass

  main:
    web-application-type: reactive

  codec:
    max-in-memory-size: 10MB

logging:
  level:
    root: INFO

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/