server:
  port: 8010

spring:
  application:
    name: msvc-auth
  config:
    import: optional:configserver:http://localhost:8888

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/auth_db
    username: auth_user
    password: auth_pass

  main:
    web-application-type: reactive

  codec:
    max-in-memory-size: 10MB

logging:
  level:
    root: INFO
    org.springframework.r2dbc.core: DEBUG
    org.springframework.security: DEBUG

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/